services:
  - type: web
    name: crm-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    branch: main
    plan: free
    envVars:
      - key: GOOGLE_CLIENT_ID
        value: 583250868510-r3e37u1i3udor8ctdo8p5s5o87qg3rol.apps.googleusercontent.com
